### ISSUE TITLE
go plugin builds failing

### ISSUE THREAD

**Issue by manedurphy** [klauspost/compress#438]
A dependency that I have utilizes this library, and builds are failing after I upgraded it. The error I am getting is one that I have received before, also seen here cespare/xxhash#54. I resolved the issue before by upgrading to cespare/xxhash v2.1.2

The error I am getting now that I have upgraded my dependencies is this
```bash
asm: xxhash_amd64.s:120: when dynamic linking, R15 is clobbered by a global variable access and is used here: 00092 (path-to-vendor/vendor/github.com/klauspost/compress/zstd/internal/xxhash/xxhash_amd64.s:120) ADDQ R15, AX
```

I noticed some differences between the files in this repository and cespare/xxhash and wonder if making them the same would resolve the issue, but unfortunately, I will not have free time to explore this further so I thought I would open the issue and ask your thoughts.

The version of Go that I am using is 1.17. Appreciate any insight on the matter.

**Comment by klauspost** [comment]
@manedurphy Upgrade. Already fixed in #430

**Comment by manedurphy** [comment]
I see. Hmm, I wonder why the build is still failing. I will have to investigate further. Thank you @klauspost
